# Usa una imagen base con TensorFlow
FROM tensorflow/tensorflow:2.12.0

# Define el directorio de trabajo dentro del contenedor
WORKDIR /app

# Instalar las bibliotecas del sistema necesarias para OpenCV
RUN apt-get update && apt-get install -y libgl1-mesa-glx libglib2.0-0

# Copiar todos los archivos del proyecto al contenedor
COPY . /app/

# Copiar el modelo de predicción al contenedor
COPY conv_MLP_84.h5 /app/conv_MLP_84.h5

# Instalar dependencias necesarias
RUN pip install --no-cache-dir \
    opencv-python==4.5.5.64 \
    numpy==1.23.5 \
    Pillow==9.5.0 \
    tensorflow

# Permitir que el contenedor acepte argumentos
ENTRYPOINT ["python", "/app/src/data/detector_neumonia.py"]
