FROM python:3.9

# Actualizar e instalar dependencias necesarias
RUN apt-get update -y && \
    apt-get install -y python3-opencv && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Definir el directorio de trabajo
WORKDIR /home/src

# Copiar los archivos del proyecto
COPY . .

# Instalar dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Comando por defecto para ejecutar el proyecto
CMD ["python", "detector_neumonia.py"]
